apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultserver-deployment
  labels:
    app: resultserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers:
      - name: resultserver
        image: aydintokuslu/phonebook_resultserver:5.0
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret       
                key: MYSQL_ROOT_PASSWORD 
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: MYSQL_DATABASE
          - name: MYSQL_DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: db-config
                key: MYSQL_DATABASE_HOST
        resources:
            limits:
              memory: 500Mi
              cpu: 100m
            requests:
              memory: 250Mi
              cpu: 80m
--- 
apiVersion: v1
kind: Service
metadata:
  name: resultserver-service
spec:
  type: NodePort
  selector:
    app: resultserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010
      