apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources: 
#   - api/api-depl.yaml
#   - api/api-service.yaml
#   - db/db-depl.yaml
#   - db/db-service.yaml

resources: 
  - api/
  - db/

commonLabels:
  department: engineering
  feature: api 

namespace: debugging

namePrefix: KodeKloud-
nameSuffix: -web 

commonAnnotations:
  logging: verbose

images:
  - name: mongo 
    newName: postgres
    newTag: "4.2"

patches:
  - target: 
      kind: Deployment 
      name: api-deployment 
    patch: |- 
      - op: replace 
        path: /metadata/name
        value: web-deployment
    # patch: |- 
    #   - op: replace 
    #     path: /spec/replicas
    #     value: 5




# kustomiza build k8s/ | kubectl apply -f -
# kubectl apply -k k8s
# kubectl delete -k k8s