apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources: 
#   - api/api-depl.yaml
#   - api/api-service.yaml
#   - db/db-depl.yaml
#   - db/db-service.yaml

# resources: 
#   - api/
#   - db/




# kustomiza build k8s/ | kubectl apply -f -
# kubectl apply -k k8s
# kubectl delete -k k8s