# Default values for dockerization-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

bookstore_image: aydintokuslu/bookstore-api:4.0
mysql_image: mysql:5.7

bookstore_service:
  type: NodePort
  port: 30001

mysql_service:
  type: ClusterIP
  port: 3306

