apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    name: mysql-service
    app: bookstore-api-app
spec:
  ports:
  - port: {{ .Values.mysql_service.port }}
    targetPort: {{ .Values.mysql_service.port }}
  selector:
     name: mysql-pod
     app: bookstore-api-app
  