apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: 
  - api-depl.yaml
  - api-service.yaml
  - db-depl.yaml
  - db-service.yaml




# kustomiza build k8s | kubectl apply -f -
# kubectl apply -k k8s
# kubectl delete -k k8s