apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultserver-deployment
  labels:
    app: resultserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers:
      - name: resultserver
        image: aydintokuslu/phonebook_resultserver:5.0
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: database
        - name: MYSQL_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: database-host
        
--- 
apiVersion: v1
kind: Service
metadata:
  name: resultserver-service
spec:
  type: NodePort
  #type: LoadBalancer
  selector:
    app: resultserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002