apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver
  name: resultserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver
  strategy: {}
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers:
      - image: aydintokuslu/proje_resultserver
        name: resultserver
        ports:
        - containerPort: 80
        envFrom:
          # - secretRef:
          #     name: mysql-secret
          - configMapRef:
              name: configmap-all
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        
