apiVersion: apps/v1
kind: Deployment
metadata:
  #name: mysql-server-pod-deploy
  name: database
  labels:
    name: mysql-server-pod-deploy
    app: phonebook-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: mysql-pod
      app: phonebook-app
  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-pod
        app: phonebook-app
    spec:
      containers:
      - name: database
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "P123456p"
        - name:  MYSQL_DATABASE
          value: "clarusway_phonebook"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "awsdevops13"
        ports:
        - containerPort: 3306