apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: app
  labels:
    name: mysql-pod
    app: phonebook-app
spec:
  containers:
  - name: database
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "P123456p"
    - name:  MYSQL_DATABASE
      value: "clarusway_phonebook"
    - name: MYSQL_USER
      value: "admin"
    - name: MYSQL_PASSWORD
      value: "awsdevops13"
    ports:
     - containerPort: 3306