apiVersion: v1
kind: Pod
metadata:
  name: web-server-pod
  labels:
    name: web-server-pod
    app: phonebook-app
spec:
  containers:
  - name: web-server
    image: aydintokuslu/phonebook_webserver:2.0
    ports:
         - containerPort: 80