apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-3g
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/Users/aydin/Desktop/Kubernetes/kubernetes-dersler/S4-kubernetes-04-pods-volumes/ikinci-deneme/pv-data"