apiVersion: v1
kind: Pod
metadata:
  name: roman-numerals-pod
  labels:
    name: roman-numerals-pod
    app: roman-numerals-app
spec:
  containers:
  - name: roman-numerals
    image: aydintokuslu/roman_numerals:2.0
    ports:
         - containerPort: 80